Las funciones propias del laplaciano tienen la forma $\phi_j(x) = sin\left(\frac{\pi jx}{N}\right), \quad j \in \{1,...,N-1\}$

In [2]:
function phi_func(N)
    phi_vect = zeros(N-1,N-1)
    for j in 1:N-1
        for x in 1:N-1
            phi_vect[j,x] = sin((pi*j*x)/(N))
        end
    end
    
    return phi_vect
end


function lambda_func(N)
    
    lambda = zeros(N-1)
    for j in 1:N-1
        lambda[j] = cos(j*pi/N)
    end
    
    return lambda
end

lambda_func(5)

4-element Vector{Float64}:
  0.8090169943749475
  0.30901699437494745
 -0.30901699437494734
 -0.8090169943749473

De hecho podemos calcular los coeficientes de la expansión de Fourier para una función arbitraria $f$ por medio de $c_j = \sum_{k=1}^{N-1}\frac{2}{N}f(k)sin\left(\frac{\pi jk}{N}\right)$

In [3]:
#Calculamos los coeficientes de f
function coeficientes(f)
    N = length(f)
    c = zeros(N)
    for j in 1:N
        for k in 1:N
            c[j] += (2/(N+1))*f[k]*sin((pi*j*k)/(N+1))
        end
    end  
    
    return c
end

#La funcion de ganancia
function G(x,k)
    
    return max(x-k,0)
    
end


N = 7
k = 2
Gvect = zeros(N-1)
for i in 1:N-1
    Gvect[i] = G(i,k)
end


iden = 1:N
func = zeros(N-1)

#Coeficientes de la función de ganancia
c = coeficientes(Gvect)

#Reconstruimos la  función de ganancia (salvo errores numéricos)
phi = phi_func(N)
for x in 1:N-1
    for j in 1:N-1 
        func[x] += c[j]*phi[j,x]
    end
end

func

6-element Vector{Float64}:
 -2.1718737919229625e-15
  1.8735013540549517e-15
  0.999999999999999
  2.0000000000000004
  3.0000000000000004
  3.9999999999999973

La solución a la ecuación del calor está dada por $p_n(y) = \sum_{j=1}^{N-1}c_j\left[cos\left(\frac{j\pi}{N}\right)\right]^n\phi_j(y)$.

In [11]:
#Calculamos la solucion a la ecuacion del calor
function sol_heat(f,n)
    N = length(f)
    p = zeros(N)
    phi = phi_func(N+1)
    c = coeficientes(f)
    lambda = lambda_func(N+1)
    for x in 1:N
        for j in 1:N
            p[x] += c[j]*(lambda[j]^n)*phi[j,x]
        end
    end
    
    return p
end


#Quitamos los terminos correspondientes a valores propios negativos
function sol_heat_plus(f,n)
    N = length(f)
    p = zeros(N)
    phi = phi_func(N+1)
    c = coeficientes(f)
    lambda = lambda_func(N+1)
    for x in 1:N
        for j in 1:N
            if lambda[j]>= 0
                p[x] += c[j]*(lambda[j]^n)*phi[j,x]
            end
        end
    end
    
    return p
end

#Solucion fundamental
n = 10
N = 5
delta = zeros(N-1)
delta[1] = 1

sol_heat(delta,50)

4-element Vector{Float64}:
 6.908910820335724e-6
 3.5575383784680614e-20
 1.1178852532545117e-5
 2.541098841762901e-20

Veamos qué pasa si escogemos a la función de valor como condición inicial.

In [13]:
k = 2
N=5
Gvect = zeros(N-1)
for i in 1:N-1
    Gvect[i] = G(i,k)
end




sol_heat_plus(Gvect,50)

4-element Vector{Float64}:
 1.2498337086608326e-5
 2.022273420898561e-5
 2.0222734208985612e-5
 1.2498337086608328e-5